name: Deploy web content to Ubuntu Server 

on: 
  push: 
    branches:
      - main 


jobs: 
  deploy: 
    runs-on: ubuntu-latest 

    steps: 
      - name: checkout Repository 
        uses: actions/checkout@v3 

      - name: Deploy To server 
        env: 
          SSH_KEY: ${{ vars.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Save the SSH private key to a file
          echo "$SSH_KEY" > private_key.pem
          chmod 400 private_key.pem
          
          # Debugging outputs (optional)
          echo "Private key saved to private_key.pem"
          echo "Connecting to server at $SERVER_IP"
          
          # Connect to the server and create a directory
           ssh -i .\private_key.pem  -o StrictHostKeyChecking=no ubuntu@34.207.122.94 "mkdir -p it_is_working_well"