name: Deploy web content to Ubuntu Server 

on: 
  push: 
    branches:
      - main 


jobs: 
  deploy: 
    runs-on: ubuntu-latest 

    steps: 
      - name: checkout Repository 
        uses: actions/checkout@v3 

      - name: Deploy To server 
        env: 
          SSH_KEY: ${{ vars.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Save the SSH private key to a file
          chmod 400 mykey
          
          # Debugging outputs (optional)
          echo "Private key saved to private_key.pem"
          echo "Connecting to server at $SERVER_IP"
          
          # This delete all file in the said location 
           ssh -i mykey  -o StrictHostKeyChecking=no ubuntu@34.207.122.94 "sudo rm -rf /var/www/html/*"

           #Copies the web content to the remote server
           scp -i mykey -r ./* ubuntu@34.207.122.94:/web

           ssh -i mykey  -o StrictHostKeyChecking=no ubuntu@34.207.122.94 "sudo cp -rf web/* /var/www/html"
           
           # This restart the nginx service
           ssh -i mykey  -o StrictHostKeyChecking=no ubuntu@34.207.122.94 "sudo systemctl restart nginx"